version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: toon-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lezhintoon
      MYSQL_DATABASE: toon
      MYSQL_USER: lezhin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:
