spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/toon?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: lezhin
    password: password

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: false
        format_sql: true
        show_sql: true
    open-in-view: false

api:
  prefix: /api/v1

jwt:
  secretKey: "lezhin-super-secret-key-lezhin-super-secret-key"
  accessTokenExpiration: 600000 # 60 * 10 * 1000 = 10minutes